FacturacioneInventario/config/routes.rb
FacturacioneInventario::Application.routes.draw do
  resources :productos

  resources :ventas

  root :to => 'productos#index'

end

FacturacioneInventario/app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :cantidad, :nombre, :precio
end

FacturacioneInventario/app/models/venta.rb
class Venta < ActiveRecord::Base
  attr_accessible :cantidad, :precio, :producto_id
end

FacturacioneInventario/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

FacturacioneInventario/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

FacturacioneInventario/app/controllers/ventas_controller.rb
class VentasController < ApplicationController
  # GET /ventas
  # GET /ventas.json
  def index
    @ventas = Venta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ventas }
    end
  end

  # GET /ventas/1
  # GET /ventas/1.json
  def show
    @venta = Venta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venta }
    end
  end

  # GET /ventas/new
  # GET /ventas/new.json
  def new
    @venta = Venta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venta }
    end
  end

  # GET /ventas/1/edit
  def edit
    @venta = Venta.find(params[:id])
  end

  # POST /ventas
  # POST /ventas.json
  def create
    @venta = Venta.new(params[:venta])
    @producto = Producto.find(params[:venta][:producto_id])
    @venta.precio = @producto.precio * @venta.cantidad
    respond_to do |format|
      if @venta.save
        @producto[:cantidad] = @producto.cantidad - params[:venta][:cantidad].to_i
        @producto.save
        format.html { redirect_to @venta, notice: 'Venta was successfully created.' }
        format.json { render :json => {:venta =>@venta, :producto =>@producto}, status: :created, location: @venta }
      else
        format.html { render action: "new" }
        format.json { render json: @venta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ventas/1
  # PUT /ventas/1.json
  def update
    @venta = Venta.find(params[:id])
    #params[:venta][:cantidad] = @venta[:cantidad] - params[:venta][:cantidad]


    respond_to do |format|
      if @venta.update_attributes(params[:venta])
        format.html { redirect_to @venta, notice: 'Venta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/1
  # DELETE /ventas/1.json
  def destroy
    @venta = Venta.find(params[:id])
    @venta.destroy

    respond_to do |format|
      format.html { redirect_to ventas_url }
      format.json { head :no_content }
    end
  end

  private
  def hay_inventario?(lista)
    lista.each do |list|
      list.delete if lista.cantidad.eql? 0
    end
  end
end

FacturacioneInventario/app/helpers/application_helper.rb
module ApplicationHelper
end

FacturacioneInventario/app/helpers/productos_helper.rb
module ProductosHelper
end

FacturacioneInventario/app/helpers/ventas_helper.rb
module VentasHelper
end

FacturacioneInventario/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacturacioneInventario</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Ver productos", productos_path %>
<%= link_to "Ver Ventas", ventas_path %>


<%= yield %>

</body>
</html>

FacturacioneInventario/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FacturacioneInventario/app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

FacturacioneInventario/app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
  <tr>
    <td><%= producto.nombre %></td>
    <td><%= producto.precio %></td>
    <td><%= producto.cantidad %></td>
    <td><%= link_to 'Show', producto %></td>
    <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
    <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producto', new_producto_path %>

FacturacioneInventario/app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

FacturacioneInventario/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @producto.nombre %>
</p>

<p>
  <b>Precio:</b>
  <%= @producto.precio %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @producto.cantidad %>
</p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

FacturacioneInventario/app/views/ventas/_form.html.erb
<%= form_for(@venta) do |f| %>
  <% if @venta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venta.errors.count, "error") %> prohibited this venta from being saved:</h2>

      <ul>
      <% @venta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto_id %><br />
    <%= f.number_field :producto_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FacturacioneInventario/app/views/ventas/edit.html.erb
<h1>Editing venta</h1>

<%= render 'form' %>

<%= link_to 'Show', @venta %> |
<%= link_to 'Back', ventas_path %>

FacturacioneInventario/app/views/ventas/index.html.erb
<h1>Listing ventas</h1>

<table>
  <tr>
    <th>Factura</th>
    <th>Producto</th>
    <th>Cantidad</th>
    <th>Precio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ventas.each do |venta| %>
  <tr>
    <td><%=  venta.id %></td>
    <td><%= venta.producto_id %></td>
    <td><%= venta.cantidad %></td>
    <td><%= venta.precio %></td>
    <td><%= link_to 'Show', venta %></td>
    <td><%= link_to 'Edit', edit_venta_path(venta) %></td>
    <td><%= link_to 'Destroy', venta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venta', new_venta_path %>

FacturacioneInventario/app/views/ventas/new.html.erb
<h1>New venta</h1>

<%= render 'form' %>

<%= link_to 'Back', ventas_path %>

FacturacioneInventario/app/views/ventas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Producto:</b>
  <%= @venta.producto_id %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @venta.cantidad %>
</p>

<p>
  <b>Precio:</b>
  <%= @venta.precio %>
</p>


<%= link_to 'Edit', edit_venta_path(@venta) %> |
<%= link_to 'Back', ventas_path %>